const express = require("express");
const cors = require("cors");
const bodyParser = require("body-parser");
// const dataRoutes = require("./routes/dataRoutes");
// const recipeGenerationEndpoint = require("./routes/recipeGenerationEndpoint");
// const recipeGenerationEndpoint2 = require("./routes/recipeGenerationEndpoint2");
// const saveRecipe = require("./routes/saveRecipe");
// const saveRecipe2 = require("./routes/saveRecipe2");
const saveUser = require("./routes/saveUser");
const updateRecipeImage = require("./routes/updateRecipeImage");
// const getRecipes = require("./routes/getRecipes");
const getSavedRecipes = require("./routes/getSavedRecipes");
const getRecipesInHistory = require("./routes/getRecipesInHistory");
// const getUserName = require("./routes/getUserName");
const getRecipe = require("./routes/getRecipe");
// const deleteRecipe = require("./routes/deleteRecipe");
// const saveRecipeToUser = require("./routes/saveRecipeToUser");
const toggleSaveRecipe = require("./routes/toggleSaveRecipe");
const saveRecipeToHistory = require("./routes/saveRecipeToHistory");
const checkIfSaved = require("./routes/checkIfSaved");
const addComment = require("./routes/addComment");
const getComments = require("./routes/getComments");
const getRecipeRatings = require("./routes/getRecipeRatings");
const rateRecipe = require("./routes/rateRecipe");
const deleteRating = require("./routes/deleteRating");
// const testToken = require("./routes/testToken");
const userInfo = require("./routes/userInfo");
const updateAvatar = require("./routes/updateAvatar");
const updateUserName = require("./routes/updateUserName");
const getUserProfile = require("./routes/getUserProfile");
const recipesIds = require("./routes/recipesIds");
const topRecipes = require("./routes/topRecipes");
const recentRecipes = require("./routes/recentRecipes");
// const recipeRoutes = require("./routes/recipeRoutes");
const search = require("./routes/search");

const app = express();

app.use(cors());
app.use(bodyParser.json());
// app.use("/api/data", dataRoutes);
// app.use("/api", saveRecipe);
// app.use("/api", saveRecipe2);
app.use("/api", saveUser);
app.use("/api", updateRecipeImage);
// app.use("/api", getRecipes);
// app.use("/api", getUserName);
app.use("/api", getRecipe);
app.use("/api", getSavedRecipes);
app.use("/api", getRecipesInHistory);
// app.use("/api", deleteRecipe);
// app.use("/api", saveRecipeToUser);
app.use("/api", toggleSaveRecipe);
app.use("/api", saveRecipeToHistory);
app.use("/api", checkIfSaved);
app.use("/api", addComment);
app.use("/api", getComments);
app.use("/api", getRecipeRatings);
app.use("/api", rateRecipe);
app.use("/api", deleteRating);
// app.use("/api", recipeGenerationEndpoint);
// app.use("/api", recipeGenerationEndpoint2);
// app.use("/api", testToken);
app.use("/api", userInfo);
app.use("/api", updateAvatar);
app.use("/api", updateUserName);
app.use("/api", getUserProfile);
app.use("/api", recipesIds);
app.use("/api", topRecipes);
app.use("/api", recentRecipes);
// app.use("/api", recipeRoutes);
app.use("/api", search);

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
